<h1 style="text-align: center">
<div style="color: #DD3403; font-size: 60%">Data Science DISCOVERY MicroProject</div>
<span style="">MicroProject #3: Highest Mountains in the World</span>
<div style="font-size: 60%;"><a href="https://discovery.cs.illinois.edu/microproject/highest-mountain/">https://discovery.cs.illinois.edu/microproject/highest-mountain/</a></div>
</h1>

<hr style="color: #DD3403;">

## Data Source: Wikipedia's "List of mountains by elevation"

Wikipedia is an ad-free, open source, and very reliable source of information about almost every topic you can imagine!  In this MicroProject, you will explore how to easily import data from any Wikipedia tables into a DataFrame.

The Wikipedia article "List of mountains by elevation" (https://en.wikipedia.org/wiki/List_of_mountains_by_elevation) contains information on hundreds of mountains -- including **Mount Everest** (tallest in the world), **Denali / Mount McKinley** (tallest in the United States), and hundreds more!
- Click the Wikipedia link above to view how the Wikipedia page looks in your web browser before we begin to work with it in Python!

Once you've taken a look at the data, let's nerd out with gathering data from Wikipedia!

### Background Knowledge

To finish this MicroProject, we assume you already know how to:

- Load a CSV file into a DataFrame using `pd.read_csv` ([review loading a CSV file](https://discovery.cs.illinois.edu/learn/Basics-of-Data-Science-with-Python/Python-for-Data-Science-Introduction-to-DataFrames/)),
- Perform simple row selection of a DataFrame ([review row selection](https://discovery.cs.illinois.edu/learn/Basics-of-Data-Science-with-Python/Row-Selection-with-DataFrames/)), and
- Work with using conditionals row selection of a DataFrame ([review conditionals with DataFrames](https://discovery.cs.illinois.edu/learn/Basics-of-Data-Science-with-Python/DataFrames-with-Conditionals/))

With that knowledge, this MicroProject will guide you through nerding out with gathering data from Wikipedia and finding some facts about the tallest mountains in the world.  Let's get started! :)

<hr style="color: #DD3403;">

## Part 1: Fetching Data From Wikipedia

The Wikipedia article "List of mountains by elevation" is organized into several tables of data:

- One table for mountains that are at least 8,000m in height,
- Another table for 7,000m mountains  (7,000m - 7,999m),
- Another table for 6,000m mountains  (6,000m - 6,999m),
- ...and so on...

The `pd.read_html(...)` function in the pandas library is designed to **read data from tables found in webpages**.

### Part 1.1: Using `pd.read_html`

In the following cell, we'll use `pd.read_html(...)` to read all of the tables from the Wikipedia page  "List of mountains by elevation" (https://en.wikipedia.org/wiki/List_of_mountains_by_elevation).  Here's a brief overview of the `pd.read_html` function:

- The `read_html` function is **very similar** to the commonly used `read_csv`.
- Instead of returning a DataFrame from a CSV file, the `read_html` returns **one DataFrame for each table on the website** as a Python list of DataFrames.  *(This means we'll have 8 different DataFrames when there are eight different tables on the Wikipedia page.*)
- Just like `read_csv`, you only need to provide the URL of the data or an HTML file that you've downloaded! 🎉


### Using an HTML file vs. Using of a URL

Historically, many sites could be easily and automatically downloaded with Python and you can use the URL inside of `pd.read_html`.  However, with the growth of AI agents scraping websites, many sites (including Wikipedia) are adding security to prevent automatic "scraping" of data.  This prevents us from having Python directly download the website and extract the data.

To use data from a site, you can save a copy of the webpage as an HTML file.  We have done that for the Wikipedia page and provided it for you as part of this MicroProject.  The file name is `List of mountains by elevation - Wikipedia.html`.

In the cell below, load the HTML page using the filename above and fetch a list of DataFrames.  Each DataFrame is a table from the Wikipedia page "List of mountains by elevation" and you will store those in the Python variable `dfList`:

In [30]:
# Fetch a list of DataFrames, where each DataFrame is a table from the Wikipedia page
# "List of mountains by elevation" store it in the Python variable `dfList`.
# The filename of the downloaded HTML page is:
#    "List of mountains by elevation - Wikipedia.html"
import pandas as pd

dfList = pd.read_html("/Users/weiyulin/Desktop/stat107/yulinw3/microproject-03-highest-mountains-in-the-world/List of mountains by elevation - Wikipedia.html")
dfList

[                          Mountain  Metres   Feet      Range  \
 0                    Mount Everest    8848  29029  Himalayas
 1                               K2    8611  28251  Karakoram
 2                    Kangchenjunga    8586  28169  Himalayas
 3                           Lhotse    8516  27940  Himalayas
 4                           Makalu    8485  27838  Himalayas
 5                          Cho Oyu    8188  26864  Himalayas
 6                       Dhaulagiri    8167  26795  Himalayas
 7                          Manaslu    8163  26781  Himalayas
 8                     Nanga Parbat    8126  26660  Himalayas
 9                        Annapurna    8091  26545  Himalayas
 10  Gasherbrum I (Hidden peak; K5)    8080  26510  Karakoram
 11                      Broad Peak    8051  26414  Karakoram
 12              Gasherbrum II (K4)    8035  26362  Karakoram
 13                    Shishapangma    8027  26335  Himalayas

                                    Location and notes
 0                                         Nepal/China
 1                                      Pakistan/China
 2                                         Nepal/India
 3   Nepal – Climbers ascend Lhotse Face in climbin...
 4                                               Nepal
 5       Nepal – Considered "easiest" eight-thousander
 6     Nepal – Presumed world's highest from 1808-1838
 7                                               Nepal
 8                                            Pakistan
 9   Nepal – First eight-thousander to be climbed (...
 10               Pakistan/China – Originally named K5
 11                                     Pakistan/China
 12               Pakistan/China – Originally named K4
 13                                              China  ,
                Mountain  Metres   Feet      Range  \
 0        Gasherbrum III    7952  26089  Karakoram
 1         Gyachung Kang    7952  26089  Himalayas
 2          Annapurna II    7937  26040  Himalayas
 3    Gasherbrum IV (K3)    7932  26024  Karakoram
 4            Himalchuli    7893  25896  Himalayas
 ..                  ...     ...    ...        ...
 130              Saipal    7031  23068  Himalayas
 131           Padmanabh    7030  23060  Himalayas
 132             Spantik    7027  23054  Karakoram
 133           Pamri Sar    7016  23018  Karakoram
 134         Khan Tengri    7010  23000  Tian Shan

                                 Location and notes
 0                                         Pakistan
 1                             Nepal (Khumbu)/China
 2                                            Nepal
 3                                         Pakistan
 4                                   Manaslu, Nepal
 ..                                             ...
 130                                          Nepal
 131                                          India
 132                                       Pakistan
 133                                       Pakistan
 134  Kyrgyzstan-Kazakhstan-China – #2 in Tian Shan

 [135 rows x 5 columns],
                          Mountain  Metres   Feet  \
 0                    Machapuchare    6993  22943
 1    Laila Peak (Haramosh Valley)    6985  22917
 2                       Kang Guru    6981  22904
 3                   Gasherbrum VI    6979  22897
 4                       Karun Kuh    6977  22890
 ..                            ...     ...    ...
 111                    Tocllaraju    6034  19797
 112                        Shayaz    6026  19770
 113                 Hualca Hualca    6025  19767
 114                      Uturunku    6020  19750
 115                    Mitre Peak    6010  19720

                                     Location and notes
 0    Annapurna Himalaya, Nepal – Officially unclimb...
 1                                  Karakoram, Pakistan
 2    Manaslu Himalaya, Nepal – 2005 avalanche kills 18
 3                                  Karakoram, Pakistan
 4                                  Karakoram, Pakistan
 ..                                                 ...
 111                                        Andes, Peru
 112                               Hindu Kush, Pakistan
 113                                        Andes, Peru
 114                                     Andes, Bolivia
 115                                Karakoram, Pakistan

 [116 rows x 4 columns],
         Mountain  Metres   Feet                  Range  \
 0     Laila Peak    5971  19590               Himalaya
 1    Mount Logan    5959  19551  Saint Elias Mountains
 2       Alpamayo    5947  19511                  Andes
 3    Cerro Lípez    5929  19452                  Andes
 4     Licancabur    5920  19420                  Andes
 ..           ...     ...    ...                    ...
 75         Janga    5051  16572     Caucasus Mountains
 76  Mount Kazbek    5055  16585     Caucasus Mountains
 77    Tungurahua    5023  16480                  Andes
 78  Carihuairazo    5018  16463                  Andes
 79    Mount Bona    5005  16421  Saint Elias Mountains

                                    Location and notes
 0                                            Pakistan
 1                   Yukon, Canada – Highest in Canada
 2                                                Peru
 3                                             Bolivia
 4                                       Bolivia/Chile
 ..                                                ...
 75  Georgia / North Caucasus, Russia – Second high...
 76             Georgia – Third highest in the country
 77                           Ecuador – Active volcano
 78                                            Ecuador
 79       Alaska, US – Also given as 5,030 m or 5,045m

 [80 rows x 5 columns],
                  Mountain  Metres   Feet  \
 0         Mount Blackburn    4996  16391
 1            Pico Bolívar    4981  16342
 2             Talgar Peak    4979  16335
 3    Shota Rustaveli Peak    4960  16270
 4           Mount Sanford    4949  16237
 ..                    ...     ...    ...
 268         Twilight Peak    4010  13160
 269           Francs Peak    4009  13153
 270          Mount Lahili    4009  13153
 271          Mount Walter    4005  13140
 272           Les Droites    4000  13000

                                     Location and notes
 0       Wrangell Mtns., Alaska, US (also given 5036 m)
 1    Sierra Nevada de Mérida, Andes, Venezuela – Hi...
 2    Tian Shan, Kazakhstan – Highest in northern Ti...
 3    Caucasus Mountains, Svaneti, Georgia/North Cau...
 4                           Wrangell Mtns., Alaska, US
 ..                                                 ...
 268                   San Juan Mountains, Colorado, US
 269                        Absaroka Range, Wyoming, US
 270                    Svaneti Range, Svaneti, Georgia
 271                                     New Mexico, US
 272                          Mont Blanc massif, France

 [273 rows x 4 columns],
                 Mountain  Metres   Feet  \
 0               Piz Zupò    3995  13107
 1           Truchas Peak    3994  13104
 2            Fletschhorn    3993  13100
 3    Mount Albert Edward    3990  13090
 4               La Meije    3987  13081
 ..                   ...     ...    ...
 350       Cathedral Peak    3004   9856
 351          Mount Tahat    3003   9852
 352              Sapitwa    3002   9849
 353          Ben Macdhui    3001   9846
 354         The Fortress    3000   9800

                          Location and notes
 0                Bernina Range, Switzerland
 1    Sangre de Cristo Mountains, New Mexico
 2                 Pennine Alps, Switzerland
 3                          Papua New Guinea
 4                     Dauphiné Alps, France
 ..                                      ...
 350                             Drakensberg
 351                       Algeria – Highest
 352                  Mulanje Massif, Malawi
 353              Eastern Cape, South Africa
 354                        Canadian Rockies

 [355 rows x 4 columns],
                  Mountain  Metres    Feet  \
 0    Tre Cime di Lavaredo  2999.0  9839.0
 1          Pizzo Centrale  2999.0  9839.0
 2        Cascade Mountain  2998.0  9836.0
 3                 Copahue  2997.0  9833.0
 4          Mount Girouard  2995.0  9826.0
 ..                    ...     ...     ...
 307       Alpe di Succiso  2017.0  6617.0
 308                   Kom  2016.0  6614.0
 309       Polar Bear Peak  2016.0  6614.0
 310          Mount Asgard  2015.0  6611.0
 311        Mount Le Conte  2010.0  6590.0

                             Location and notes
 0                   Province of Belluno, Italy
 1                                  Switzerland
 2    Vermilion Range, Canadian Rockies, Canada
 3                       Andes, Argentina/Chile
 4    Fairholme Range, Canadian Rockies, Canada
 ..                                         ...
 307            Province of Reggio Emilia Italy
 308                  Balkan Mountain, Bulgaria
 309              Chugach Mountains, Alaska, US
 310          Baffin Mountains, Nunavut, Canada
 311       Great Smoky Mountains, Tennessee, US

 [312 rows x 4 columns],
              Mountain  Metres    Feet                     Location and notes
 0    Serra da Estrela  1993.0  6539.0                               Portugal
 1        Mount Bogong  1986.0  6516.0        Australia – Highest in Victoria
 2     Mount Ishizuchi  1982.0  6503.0       Japan – Tallest in Western Japan
 3         Doi Phu Kha  1980.0  6500.0          Luang Prabang Range, Thailand
 4     Pizzo Carbonara  1979.0  6493.0             Province of Palermo Sicily
 ..                ...     ...     ...                                    ...
 229         Munboksan  1015.0  3330.0                            South Korea
 230             Kékes  1014.0  3327.0  Hungary – Highest mountain in Hungary
 231     Mount Belumut  1010.0  3310.0                        Johor, Malaysia
 232  Old Rag Mountain  1001.0  3284.0                           Virginia, US
 233      Devil's Peak  1000.0  3300.0                Cape Town, South Africa

 [234 rows x 4 columns],
                 Mountain  Metres  Feet                 Range  \
 0            Sgurr Dearg   986.0  3235               Cuillin
 1            Mount Sizer   980.0  3220          Diablo Range
 2            Mount Valin   980.0  3220  Saguenay Lac St-Jean
 3             Hyangnosan   979.0  3212                   NaN
 4           Scafell Pike   978.0  3209        Southern Fells
 ..                   ...     ...   ...                   ...
 127  Mount Ngerchelchuus   242.0   794                   NaN
 128          Mount Royal   233.0   764                   NaN
 129         Diamond Head   232.0   761                   NaN
 130            Yeomposan   203.0   666                   NaN
 131            Hamwolsan   200.0   660                   NaN

                          Location and notes
 0                                  Scotland
 1                           US (California)
 2                           Canada (Québec)
 3           Gyeongnam Province, South Korea
 4    England (Cumbria) – Highest in England
 ..                                      ...
 127        Babeldaob, Palau – Highest point
 128                          Quebec, Canada
 129                             US (Hawaii)
 130                      Ulsan, South Korea
 131                      Ulsan, South Korea

 [132 rows x 5 columns]]

### 🔬 Checkpoint Tests 🔬

In [31]:
### TEST CASE for Part 1.1: Using pd.read_html
#
# What is this cell?
# - This cell contains test cases for the MicroProject.  You can modify anything except
#   the first line of this cell, but we will replace this cell with a new version of this
#   cell when your MicroProject is graded.  It's usually best to not change this cell!
#
# - To run the test cases we have for you, just run this Python cell like any other cell! :)
#
# - If this cell runs without any error in the output, you PASSED all test cases!
#   We try and make these test cases as useful and complete as possible, but there is
#   a chance your code may be incorrect even though you pass the test cases (these
#   tests should be seen as a way to give you confidence that code you understand how
#   it works is actually correct, not as a robust check to catch all possible errors).
#
# - If this cell results in any errors, check you previous cells, make changes, and
#   RE-RUN your code and then re-run this cell.  Keep repeating this until the cell
#   passed with no errors! :)
#
# - You will find more cells that begin with the words "TEST CASE" throughout the
#   notebook at important points to make sure everything is looking good so far!
#

tada = "\N{PARTY POPPER}"

assert("dfList" in vars()), "You must define a Python variable called `dfList`."
assert(type(dfList) == type([])), "Your Python variable `dfList` must contain a list."
assert(type(dfList[0]) == type(pd.DataFrame())), "Your Python variable `dfList` must contain a list of DataFrames."
assert("Feet" in dfList[0]), "Your Python variable `dfList` must be from the Wikipedia page 'List of mountains by elevation'."
assert("Range" in dfList[1]), "Your Python variable `dfList` must be from the Wikipedia page 'List of mountains by elevation'."
assert("Mountain" in dfList[2]), "Your Python variable `dfList` must be from the Wikipedia page 'List of mountains by elevation'."
assert("Location and notes" in dfList[3]), "Your Python variable `dfList` must be from the Wikipedia page 'List of mountains by elevation'."
assert("Metres" in dfList[4]), "Your Python variable `dfList` must be from the Wikipedia page 'List of mountains by elevation'."

print(f"{tada} All Tests Passed! {tada}")

🎉 All Tests Passed! 🎉

### Part 1.2: Exploring the List of DataFrames

Your variable `dfList` contains a **Python `list`** of several DataFrames, one DataFrame for each table on the webpage.  To use this as one complete dataset, we need to join the lists together into one large DataFrame.

Before we do that, let's explore the individual DataFrames.  To look at the first item a `list`, we access the `0th` index of the list by using the Python code:

> ```py
> # Accesses the first element (index 0) of a list called `myList`
> myList[0]
> ```

Applying this to the variable `dfList`, the following code displays the first DataFrame stored in `dfList`.  This first DataFrame contains the data from the first table on the Wikipedia page:

In [32]:
dfList[0]

,Mountain,Metres,Feet,Range,Location and notes
0,Mount Everest,8848,29029,Himalayas,Nepal/China
1,K2,8611,28251,Karakoram,Pakistan/China
2,Kangchenjunga,8586,28169,Himalayas,Nepal/India
3,Lhotse,8516,27940,Himalayas,Nepal – Climbers ascend Lhotse Face in climbin...
4,Makalu,8485,27838,Himalayas,Nepal
5,Cho Oyu,8188,26864,Himalayas,"Nepal – Considered ""easiest"" eight-thousander"
6,Dhaulagiri,8167,26795,Himalayas,Nepal – Presumed world's highest from 1808-1838
7,Manaslu,8163,26781,Himalayas,Nepal
8,Nanga Parbat,8126,26660,Himalayas,Pakistan
9,Annapurna,8091,26545,Himalayas,Nepal – First eight-thousander to be climbed (...
10,Gasherbrum I (Hidden peak; K5),8080,26510,Karakoram,Pakistan/China – Originally named K5
11,Broad Peak,8051,26414,Karakoram,Pakistan/China
12,Gasherbrum II (K4),8035,26362,Karakoram,Pakistan/China – Originally named K4
13,Shishapangma,8027,26335,Himalayas,China

The second DataFrame is accessed at index `[1]`:

In [33]:
dfList[1]

,Mountain,Metres,Feet,Range,Location and notes
0,Gasherbrum III,7952,26089,Karakoram,Pakistan
1,Gyachung Kang,7952,26089,Himalayas,Nepal (Khumbu)/China
2,Annapurna II,7937,26040,Himalayas,Nepal
3,Gasherbrum IV (K3),7932,26024,Karakoram,Pakistan
4,Himalchuli,7893,25896,Himalayas,"Manaslu, Nepal"
...,...,...,...,...,...
130,Saipal,7031,23068,Himalayas,Nepal
131,Padmanabh,7030,23060,Himalayas,India
132,Spantik,7027,23054,Karakoram,Pakistan
133,Pamri Sar,7016,23018,Karakoram,Pakistan
134,Khan Tengri,7010,23000,Tian Shan,Kyrgyzstan-Kazakhstan-China – #2 in Tian Shan

Continue to look at each index, until you find the **very last DataFrame** in the list that contains data about the mountains.  *(We'll need to know the last index for the next section.)*

In [34]:
# Display the very last DataFrame containing data about the mountains from Wikipedia:
dfList[3]

,Mountain,Metres,Feet,Range,Location and notes
0,Laila Peak,5971,19590,Himalaya,Pakistan
1,Mount Logan,5959,19551,Saint Elias Mountains,"Yukon, Canada – Highest in Canada"
2,Alpamayo,5947,19511,Andes,Peru
3,Cerro Lípez,5929,19452,Andes,Bolivia
4,Licancabur,5920,19420,Andes,Bolivia/Chile
...,...,...,...,...,...
75,Janga,5051,16572,Caucasus Mountains,"Georgia / North Caucasus, Russia – Second high..."
76,Mount Kazbek,5055,16585,Caucasus Mountains,Georgia – Third highest in the country
77,Tungurahua,5023,16480,Andes,Ecuador – Active volcano
78,Carihuairazo,5018,16463,Andes,Ecuador
79,Mount Bona,5005,16421,Saint Elias Mountains,"Alaska, US – Also given as 5,030 m or 5,045m"

### Part 1.3: Joining the individual DataFrames into one large DataFrame

Before we can do analysis on the whole dataset, we need to join the individual DataFrames together into one large DataFrame.  When we join DataFrames end-to-end, where the last row of the previous DataFrame is followed by the first row of the next DataFrame, the operation is called **concatenation**.

Read the DISCOVERY guide to learn the syntax on "Combining DataFrames by Concatenation"
- [DISCOVERY Guide: "Combining DataFrames by Concatenation"](https://discovery.cs.illinois.edu/guides/Combining-DataFrames/Combining-DataFrames-by-Concatenation/)
- https://discovery.cs.illinois.edu/guides/Combining-DataFrames/Combining-DataFrames-by-Concatenation/

Use concatenation to create a single DataFrame `df` that contains data about every mountain found on the Wikipedia page:

In [43]:
import pandas as pd

df = pd.concat(dfList).reset_index(drop=True)
df

,Mountain,Metres,Feet,Range,Location and notes
0,Mount Everest,8848.0,29029.0,Himalayas,Nepal/China
1,K2,8611.0,28251.0,Karakoram,Pakistan/China
2,Kangchenjunga,8586.0,28169.0,Himalayas,Nepal/India
3,Lhotse,8516.0,27940.0,Himalayas,Nepal – Climbers ascend Lhotse Face in climbin...
4,Makalu,8485.0,27838.0,Himalayas,Nepal
...,...,...,...,...,...
1646,Mount Ngerchelchuus,242.0,794.0,NaN,"Babeldaob, Palau – Highest point"
1647,Mount Royal,233.0,764.0,NaN,"Quebec, Canada"
1648,Diamond Head,232.0,761.0,NaN,US (Hawaii)
1649,Yeomposan,203.0,666.0,NaN,"Ulsan, South Korea"
1650,Hamwolsan,200.0,660.0,NaN,"Ulsan, South Korea"

### 🔬 Checkpoint Tests 🔬

In [44]:
### TEST CASE for Part 1.3: Joining the individual DataFrames into one large DataFrame
tada = "\N{PARTY POPPER}"

assert("df" in vars()), "You must create a variable called `df` that is a single DataFrame (not a list)."
assert(type(dfList) == type([])), "You must NOT override `dfList`.  The variable `dfList` must still be a DataFrame for each table on Wikipedia."
assert(len(df) > len(dfList[0])), "You must concat all of the DataFrames together into one large DataFrame `df`."
assert("Feet" in df), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`."
assert("Mountain" in df), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`."
assert("Hindu Kush" in df["Range"].values), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert("K2" in df["Mountain"].values), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert("Batura Sar" in df["Mountain"].values), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert("Meru Peak" in df["Mountain"].values), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert("Ubinas" in df["Mountain"].values), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert(len(df) > 1600 and len(df) < 1700), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"
assert(len(df[ df["Location and notes"].str.contains("Himalayas")]) == 35), "Your DataFrame stored in the variable `df` must be a concatenation of all the individual DataFrames in `dfList`.  (You are missing at least one table.)"

print(f"{tada} All Tests Passed! {tada}")

🎉 All Tests Passed! 🎉

<hr style="color: #DD3403;">

## Part 2: Mountains in the United States

Now that we have every mountain in a single DataFrame, we can do some analysis!

In the dataset, the `Location and Notes` column contains a human-written description of the location and other notes.  For example, the notes about the mountain "Makalu" notes that the mountain is in "Nepal".

To do the next analysis, we want to select from all the mountains in the entire dataset `df` and find only the mountains located in the United States.

To do this, you'll need to do two things:

1. First, look back at the [Wikipedia page](https://en.wikipedia.org/wiki/List_of_mountains_by_elevation), or explore `df` here in Python, to find out **all the different ways mountains in the United States might be labeled**.  *(Hint: There's two different ways!)*
2. Second, read the DISCOVERY guide to learn the syntax on "Selecting DataFrame Rows Based on String Contents" to identify how we can use the two different ways the United States is labeled:
    - [DISCOVERY Guide: "Selecting DataFrame Rows Based on String Contents"](https://discovery.cs.illinois.edu/guides/DataFrame-Row-Selection/dataframe-string-contains/)
    - https://discovery.cs.illinois.edu/guides/DataFrame-Row-Selection/dataframe-string-contains/

Create a DataFrame of only the mountains in the United States and store it in the variable `df_us` in the cell below.

In [49]:
# Create a DataFrame of only the mountains in the United States and store it in the variable `df_us`:
df_us = df[df['Location and notes'].str.contains("US")| (df['Location and notes'].str.contains("United States"))]
df_us

,Mountain,Metres,Feet,Range,Location and notes
245,Denali (Mount McKinley),6190.0,20310.0,NaN,"Alaska Range, United States (Alaska) – Highest..."
298,Mount Saint Elias,5489.0,18009.0,Saint Elias Mountains,"Yukon, Canada/Alaska, US – Second highest in b..."
315,Mount Foraker,5304.0,17402.0,Alaska Range,"Alaska, US"
344,Mount Bona,5005.0,16421.0,Saint Elias Mountains,"Alaska, US – Also given as 5,030 m or 5,045m"
345,Mount Blackburn,4996.0,16391.0,NaN,"Wrangell Mtns., Alaska, US (also given 5036 m)"
...,...,...,...,...,...
1608,Taum Sauk Mountain,540.0,1770.0,NaN,"Missouri, US"
1616,Little Si,480.0,1570.0,Cascade Range,"Washington, US"
1626,Storm King Mountain,408.0,1339.0,Hudson Highlands,US (New York)
1645,Jerimoth Hill,247.0,810.0,NaN,"Rhode Island, US"
1648,Diamond Head,232.0,761.0,NaN,US (Hawaii)

### Part 2 Analysis: Percentage of Mountains in the Dataset in the United States?

What percentage of mountains in the entire dataset are found in the United States?

In [54]:
pct_us = 348/1651
pct_us

0.21078134463961234

### 🔬 Checkpoint Tests 🔬

In [55]:
### TEST CASE for Part 2: Mountains in the United States
tada = "\N{PARTY POPPER}"

assert("df_us" in vars()), "You must create a variable called `df_us`."
assert(len(df_us) > 300 and len(df_us) < 400), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."
assert(len(df_us[ df_us.Mountain.str.contains("Mount Saint Elias")]) == 1), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."
assert(len(df_us[ df_us.Mountain.str.contains("Denali")]) == 1), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."
assert("Ubinas" not in df_us["Mountain"]), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."
assert("Carihuairazo" not in df_us["Mountain"]), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."
assert("Sirbal Peak" not in df_us["Mountain"]), "You DataFrame must contain ALL mountains in the United States. It appears you have not identified the two different ways that the United States appears in the Wikipedia tables."

assert("pct_us" in vars()), "You must create a variable called `pct_us`."
assert(pct_us > 0 and pct_us < 1), "The variable called `pct_us` must contain a percentage between 0 and 1."
assert(pct_us == len(df_us) / len(df)), "The variable called `pct_us` must contain the percentage of mountains in the United States among all the mountains in the dataset."

print(f"{tada} All Tests Passed! {tada}")

🎉 All Tests Passed! 🎉

<hr style="color: #DD3403;">

## Part 3: Higher than the Highest Mountain in the United States

You have identified the highest mountains in the United States, and also have the data for the highest mountains across the world! 🎉

In the final puzzle for this MicroProject, create a DataFrame that contains **ALL** of the mountains that have a height that is higher than the highest mountain in the United States.  Store the DataFrame in the Python variable `df_higherThanUS`:

In [19]:
# Store your new DataFrame in the variable `df_higherThanUS`:

df_us = df[df["Location and notes"].str.contains("US|United States|Alaska")]

us_max_height = df_us["Feet"].max()

df_higherThanUS = df[df["Feet"] > us_max_height]


print(df_higherThanUS[["Mountain", "Feet", "Location and notes"]])

Empty DataFrame
Columns: [Mountain, Feet, Location and notes]
Index: []

### Part 3 Visualization: Heights of Various Mountains

A bar chart is a great way to visualize data that contains non-numeric data or categories.  In this MicroProject, you have explored the height of various mountains -- let's visualize just how tall Mount Everest compared to other mountains in this dataset.

Since there are over 1,000 mountains in the dataset, our visualization will show a subset of all the mountains.  Specifically, we'll visualize **every 49th mountain** -- indexes `[0]`, `[49]`, `[98]`, `[147]`, `[196]`, etc.

Selecting only every 61st mountain can be done by selecting a range from your DataFrame with the following format:
> ```py
> # Selects every 61st row, starting with [0]:
> df[::49]
> ```

Creating a bar chart from a DataFrame is done by using the general format:

> ```py
> # Generic format for a bar chart from a DataFrame:
> df.plot.bar(x="data-column-name", y="data-column-name")
> ```

Combining these together, your bar chart can be created with the general format:

> ```py
> # Generic format for a bar chart of every 61st row of a DataFrame:
> df[::49].plot.bar(x="data-column-name", y="data-column-name")
> ```

#### Create Your Visualization

Create a bar chart below, using the mountain name for your `x`-axis data and the height (either feet or meters, your choice!) for the `y`-axis data:

In [23]:
# Create a bar chart
# - using the mountain name for your `x`-axis data, and
# - using the height (either feet or meters, your choice!) for the `y`-axis data
!pip install matplotlib beautifulsoup4 lxml html5lib

import pandas as pd

tables = pd.read_html("/Users/weiyulin/Desktop/stat107/yulinw3/microproject-03-highest-mountains-in-the-world/List of mountains by elevation - Wikipedia.html")
df = tables[0]


df_us = df[df["Location and notes"].str.contains("US|United States|Alaska", case=False, na=False)]


us_max_height = df_us["Feet"].max()


df_higherThanUS = df[df["Feet"] > us_max_height]


print("Highest mountain in the US:")
print(df_us[["Mountain", "Feet", "Location and notes"]].sort_values("Feet", ascending=False).head(1))

print("\nMountains higher than the highest mountain in the US:")
print(df_higherThanUS[["Mountain", "Feet", "Location and notes"]])

Requirement already satisfied: matplotlib in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (3.10.6)
Requirement already satisfied: beautifulsoup4 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (4.13.5)
Requirement already satisfied: lxml in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (6.0.1)
Requirement already satisfied: html5lib in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (1.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (2.3.3)
Requirement already satisfied: packaging>=20.0 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (3.2.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: soupsieve>1.2 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six>=1.9 in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /Users/weiyulin/Desktop/stat107/yulinw3/.venv/lib/python3.11/site-packages (from html5lib) (0.5.1)
Highest mountain in the US:
  Mountain   Feet                             Location and notes
5  Cho Oyu  26864  Nepal – Considered "easiest" eight-thousander

Mountains higher than the highest mountain in the US:
        Mountain   Feet                                 Location and notes
0  Mount Everest  29029                                        Nepal/China
1             K2  28251                                     Pakistan/China
2  Kangchenjunga  28169                                        Nepal/India
3         Lhotse  27940  Nepal – Climbers ascend Lhotse Face in climbin...
4         Makalu  27838                                              Nepal

### 🔬 Checkpoint Tests 🔬

In [24]:
### TEST CASE for Part 3: Higher than the Highest Mountain in the United States
tada = "\N{PARTY POPPER}"

assert("df_higherThanUS" in vars()), "You must create a variable called `df_higherThanUS`."
assert( len(list(set(df_higherThanUS["Mountain"]) & set(df_us["Mountain"]))) == 0 ), "Some of the mountains in `df_higherThanUS` are in the United States, but there should be none."
assert( len(df_higherThanUS) == len(df[ df.Feet > df_us.sort_values("Feet", ascending=False).iloc[0].Feet ]) ), "There are some mountains in `df_higherThanUS` that are shorter than the highest mountain in the United States, but there should be none."

print(f"{tada} All Tests Passed! {tada}")

🎉 All Tests Passed! 🎉

<hr style="color: #DD3403;">

## Submission

You're almost done!  All you need to do is to commit your lab to GitHub and run the GitHub Actions Grader:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and return to https://discovery.cs.illinois.edu/microproject/highest-mountain/ and complete the section **"Commit and Grade Your Notebook"**.

3. If you see a 100% grade result on your GitHub Action, you've completed this MicroProject! 🎉